# Generated by Django 4.2.30 on 2026-05-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
