# Generated by Django 4.2.30 on 2026-05-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wifiuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wifiuser',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
