# Generated by Django 6.0.5 on 2026-06-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wifiuser_full_name_wifiuser_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
