# Generated by Django 6.0.5 on 2026-06-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session_device_type_session_framed_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='NetPulse Estate WiFi', max_length=200)),
                ('location', models.CharField(default='Greenview Estate, Ruiru', max_length=200)),
                ('admin_phone', models.CharField(default='0712 000 000', max_length=20)),
                ('mpesa_shortcode', models.CharField(default='522522', max_length=20)),
                ('renewal_reminder_days', models.IntegerField(default=2)),
                ('grace_period_hours', models.IntegerField(default=24)),
                ('auto_suspend_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
